### ISSUE TITLE
/lists/index.ts page

### ISSUE THREAD

**Issue by dincohen92** [blueocean-rico/gopher#22]
**Summary**
create lists page
![image](https://user-images.githubusercontent.com/16127198/176576141-2ef8879a-ba73-49f4-bb41-e16e79aca4fa.png)

**Difficulty**: 3

**Details**
Create a lists page that shows all of the users lists, notifications for those lists, and a button to navigate to the new list form

**Components**
- [x] list card
- [x] notifications list
- [x] notification card
- [x] new list button

**Comment by slargman** [comment]
I'm going to get started on this. Not going to take on the whole thing right now, but I'll work up setting up the data fetching so that information needed by subcomponents is available.

**Comment by slargman** [comment]
Fetching is set up.
